# Порт на якому працює Spring Boot
server.port=8081

# ✅ MariaDB підключення
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/spu123?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true
spring.datasource.username=root
spring.datasource.password=root

# ✅ Діалект для MariaDB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Автоматично створює таблиці якщо їх немає
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true

spring.servlet.multipart.max-file-size=50MB